const labels = {
  tr: {
    title: "FINANSAL EKSTRE VE ANALIZ RAPORU",
    desc: "Bu rapor kullanici tarafindan olusturulmustur.",
    user: "Kullanici",
    date: "Tarih",
    income: "GELIR",
    expense: "GIDER",
    totalIncome: "TOPLAM GELIR",
    totalExpense: "TOPLAM GIDER",
    balance: "NET BAKIYE",
    headers: ["ID", "Baslik", "Kategori", "Tutar", "Tarih", "Tip"],
    page: "Sayfa"
  },
  en: {
    title: "FINANCIAL STATEMENT & ANALYSIS",
    desc: "This report is automatically generated by the system.",
    user: "User",
    date: "Date",
    income: "INCOME",
    expense: "EXPENSE",
    totalIncome: "TOTAL INCOME",
    totalExpense: "TOTAL EXPENSE",
    balance: "NET BALANCE",
    headers: ["ID", "Title", "Category", "Amount", "Date", "Type"],
    page: "Page"
  }
};

export const exportToPDF = async (transactions, username, lang = "tr") => {
  const [{ jsPDF }, { default: autoTable }] = await Promise.all([
    import("jspdf"),
    import("jspdf-autotable")
  ]);

  const L = labels[lang] || labels.tr;
  const doc = new jsPDF();

  const income = transactions.filter(t => t.type === "income").reduce((acc, t) => acc + Number(t.amount), 0);
  const expense = transactions.filter(t => t.type === "expense").reduce((acc, t) => acc + Number(t.amount), 0);
  const balance = income - expense;

  const primaryColor = [15, 23, 42];

  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.setTextColor(primaryColor[0], primaryColor[1], primaryColor[2]);
  doc.text(L.title, 14, 22);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(120, 120, 120);
  doc.text(L.desc, 14, 28);

  doc.setFontSize(10);
  doc.setTextColor(50, 50, 50);
  doc.text(`${L.user}: @${username}   |   ${L.date}: ${new Date().toLocaleDateString('tr-TR')}`, 14, 36);

  const drawCard = (x, y, w, h, title, amount, amountColor) => {
    doc.setDrawColor(226, 232, 240);
    doc.setFillColor(248, 250, 252);
    doc.roundedRect(x, y, w, h, 3, 3, 'FD');

    doc.setFont("helvetica", "bold");
    doc.setFontSize(9);
    doc.setTextColor(100, 113, 129);
    doc.text(title, x + 6, y + 9);

    doc.setFontSize(14);
    doc.setTextColor(amountColor[0], amountColor[1], amountColor[2]);
    doc.text(`${amount.toLocaleString()} TL`, x + 6, y + 19);
  };

  drawCard(14, 44, 56, 26, L.totalIncome, income, [16, 185, 129]);
  drawCard(75, 44, 56, 26, L.totalExpense, expense, [239, 68, 68]);
  drawCard(136, 44, 60, 26, L.balance, balance, [15, 23, 42]);

  const tableRows = transactions.map(tx => [
    String(tx.id).slice(-6),
    tx.title,
    tx.category.toUpperCase(),
    `${Number(tx.amount).toLocaleString()} ${tx.currency || 'TRY'}`,
    tx.date,
    tx.type === 'income' ? L.income : L.expense
  ]);

  autoTable(doc, {
    startY: 78,
    head: [L.headers],
    body: tableRows,
    theme: 'grid',
    headStyles: {
      fillColor: primaryColor,
      textColor: 255,
      fontStyle: 'bold',
      halign: 'center',
      cellPadding: 5
    },
    bodyStyles: {
      fontSize: 10,
      textColor: [50, 50, 50],
      cellPadding: 4
    },
    columnStyles: {
      0: { halign: 'center', fontStyle: 'bold', textColor: [120, 120, 120] },
      3: { halign: 'right', fontStyle: 'bold' },
      4: { halign: 'center' },
      5: { halign: 'center', fontStyle: 'bold' }
    },
    alternateRowStyles: { fillColor: [248, 250, 252] },
    didParseCell: function (data) {
      if (data.section === 'body' && data.column.index === 5) {
        if (data.cell.raw === L.income) {
          data.cell.styles.textColor = [16, 185, 129];
        } else {
          data.cell.styles.textColor = [239, 68, 68];
        }
      }
    },
    didDrawPage: function (data) {
      doc.setFontSize(8);
      doc.setTextColor(150);
      doc.text(
        `${L.page} ${doc.internal.getNumberOfPages()}`,
        data.settings.margin.left,
        doc.internal.pageSize.height - 10
      );
    }
  });

  doc.save(`Finansal_Rapor_@${username}.pdf`);
};

export const exportToExcel = async (transactions, username, lang = "tr") => {
  const XLSX = await import("xlsx");

  const income = transactions.filter(t => t.type === "income").reduce((acc, t) => acc + Number(t.amount), 0);
  const expense = transactions.filter(t => t.type === "expense").reduce((acc, t) => acc + Number(t.amount), 0);
  const balance = income - expense;

  const excelData = [
    ["FINANSAL ANALIZ RAPORU"],
    [`Kullanici: @${username}`, `Tarih: ${new Date().toLocaleDateString('tr-TR')}`],
    [],
    ["--- OZET BAKIYE DURUMU ---"],
    ["Toplam Gelir:", `${income} TL`],
    ["Toplam Gider:", `${expense} TL`],
    ["Net Bakiye:", `${balance} TL`],
    [],
    ["ID", "Baslik", "Kategori", "Tutar", "Para Birimi", "Tarih", "Tip"]
  ];

  transactions.forEach(t => {
    excelData.push([
      String(t.id).slice(-6),
      t.title,
      t.category.toUpperCase(),
      Number(t.amount),
      t.currency || 'TRY',
      t.date,
      t.type === 'income' ? (lang === 'tr' ? 'GELİR' : 'INCOME') : (lang === 'tr' ? 'GİDER' : 'EXPENSE')
    ]);
  });

  const ws = XLSX.utils.aoa_to_sheet(excelData);

  ws['!cols'] = [
    { wch: 10 },
    { wch: 30 },
    { wch: 15 },
    { wch: 15 },
    { wch: 12 },
    { wch: 15 },
    { wch: 15 }
  ];

  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, ws, "Islemler");
  XLSX.writeFile(wb, `Finansal_Rapor_@${username}.xlsx`);
};